dataset:
  name: Autism_split_valid_2D_mid_sagittal
  type: ddpm_augmented
  image_size: 256
  split: predefined        # IMPORTANT
  train_dir: data/Autism_split_valid_2D_mid_sagittal/train
  test_dir: data/Autism_split_valid_2D_mid_sagittal/test
  classes:
    - autistic
    - non-autistic

features:
  total_extracted: 274
  rf_selected: 40


models:
  knn_neighbors: [3,5,7,9]
  svm_kernels:
    - linear
    - rbf
    - poly
  rf_estimators: 300

augmentation:
  enabled: true
  type: ddpm
  mode: offline
  source: pretrained
  applied_on: training_only
  noise_steps: 10