dataset:
  name: augmented_train_500
  type: ddpm_augmented
  image_size: 256
  split: predefined        # IMPORTANT
  train_dir: data/augmented_train_500/train
  test_dir: data/augmented_train_500/test
  classes:
    - Autism
    - Control

features:
  total_extracted: 274
  selection_method: random_forest
  ct_best: 20
  knn_best: 10
  svm_best: 20


models:
  knn_neighbors: 3
  svm_kernel: linear
  rf_estimators: 300

augmentation:
  enabled: true
  type: ddpm
  mode: offline
  source: pretrained
  applied_on: training_only
  noise_steps: 10